### ISSUE TITLE
zabbix4.0可以用吗？

### ISSUE THREAD

**Issue by stayclose1** [BillWang139967/zabbix_manager#10]

**Comment by stayclose1** [comment]
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 2553, in <module>
    zabbix=zabbix_api(terminal_table,debug,output_sort=output_sort,sort_reverse=sort_reverse,profile = profile)
  File "/usr/bin/zabbix_api", line 81, in __init__
    self.zapi.login(self.user,self.password)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 209, in login
    result = self.do_request(obj)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 265, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found

**Comment by meetbill** [comment]
没有进行测试过

Zabbix API 接口上基本是向下兼容的，应该可以使用的

**Comment by stayclose1** [comment]
> 没有进行测试过
> 
> Zabbix API 接口上基本是向下兼容的，应该可以使用的

4.0可以用。
请教两个问题
 --hostid --hostgroupid不可以同时使用吗？比如说根据--hostgroupid 查出对应的hostid，好像没用。
另外出的excel怎么把里面测试的那个图片去掉呢？

**Comment by meetbill** [comment]
Q:excel怎么把里面测试的那个图片去掉

A:
设置 /etc/zabbix_tool/zabbix_setting.ini

设置如下参数试试
```
logo_show = False
```

**Comment by meetbill** [comment]
Q:根据--hostgroupid 查出对应的hostid
A:没明白

**Comment by stayclose1** [comment]
> Q:根据--hostgroupid 查出对应的hostid
> A:没明白

zabbix_api --report "CPU" "2019-03-05 00:00:00" "2019-03-06 00:00:00"  --table --hostgroupid x --hostid xxx
不能同时使用，出的数据是all的部分。

**Comment by meetbill** [comment]
--hostgroupid 和  --hostid 取得是并集，不是交集

如果想要获取特定 hostid 的话，只需要加 --hostid 即可
