### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by lingroger** [BillWang139967/zabbix_manager#4]
当Zabbix路径为 http://xxx.xxx.xxx.xxx/zabbix 出现下列错误：
如果我在Apache上修改地址改为 http://xxx.xxx.xxx.xxx，就可以正常获取到信息。

[root@Zabbix01 zabbix_manager]# zabbix_api host_get --table
zabbix_manager:[1.4.01]
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 2530, in <module>
    zabbix=zabbix_api(terminal_table,debug,output_sort=output_sort,sort_reverse=sort_reverse,profile = profile)
  File "/usr/bin/zabbix_api", line 81, in __init__
    self.zapi.login(self.user,self.password)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 209, in login
    result = self.do_request(obj)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 265, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found

**Comment by BillWang139967** [comment]
/etc/zabbix_tool/zabbix_setting.ini
修改如下
apache=True

**Comment by lingroger** [comment]
是我没注意，谢谢。

**Comment by ld1978** [comment]
配置完成apache=True后，还报这个错
[root@localhost MySQL-python-1.2.5]# zabbix_api hostgroup_get --table
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 16, in <module>
    from w_lib.zabbix_api_lib import ZabbixAPI
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 1
    e This is a port of the ruby zabbix api found here:
