### ISSUE TITLE
根据key导出报表时报错了，zabbix版本是3.4，db用的是oracle。

### ISSUE THREAD

**Issue by dxwwp** [BillWang139967/zabbix_manager#9]
# zabbix_api --report_key "system.cpu.util\[,idle\]" "2018-11-07 01:00:00" "2018-11-07 02:00:00" --table --hostgroupid 45
zabbix_manager:[1.4.04]
:OC-NS

       Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 2610, in <module>
    zabbix._report_key(args.report_key[0],args.report_key[1],args.report_key[2],export_xls,select_condition)
  File "/usr/bin/zabbix_api", line 1050, in _report_key
    itemid_all_list = self.__item_get2(host_info[0],item_key)
  File "/usr/bin/zabbix_api", line 658, in __item_get2
    "monitored":True,
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 333, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 81, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 340, in do_request
    return self.parent.do_request(req)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 257, in do_request
    raise APITimeout("HTTP read timeout",)
w_lib.zabbix_api_lib.APITimeout: HTTP read timeout

PS:直接zabbix_api --report的不报错，但是获取的数据都是0.

**Comment by meetbill** [comment]
获取单台机器信息可以正常输出吗？ --hostid
